// Import from package.json
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import MainLayout from "@/components/layouts/MainLayout";

// Import from file
import "./globals.css";

// Text Font
const dmSans = DM_Sans({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "SKS Portal",
  description: "Generated by create next app, portal platform with health dashboard",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        <MainLayout>
          <div className="flex min-h-screen flex-col bg-blue-50">
            {children}
          </div>
        </MainLayout>
      </body>
    </html>
  );
}
