name: Jest Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Execute Jest Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Set this to the node version you are using

      - name: Install dependencies
        run: npm ci # 'npm ci' is preferred in CI environments for its speed and reliability

      - name: Run Jest
        run: npm run unit # Assuming 'npm run unit' points to 'jest' in your package.json

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always() # Ensure this step runs even if the tests fail
        with:
          name: jest-test-results
          path: coverage/ # Adjust this if your Jest configuration outputs to a different directory
